on:
    push:
      branches:
      -  main
jobs:
    build-job:
        runs-on: ubuntu-22.04

        steps:

        - name: Install CMake
          run: sudo apt-get update -y && sudo apt-get install -y cmake
        
        - name: Checkout Main Branch
          uses: actions/checkout@v4
        
        - name: list files
          run: ls -la
          
        - name: Build C++ Code
          run: |
            cd practice_code/cpp_examples
            mkdir build
            cd build
            cmake ..
            cmake --build .
        - name: Check build status
          if: ${{ failure() }}
          run: |
            echo "C++ build failed!"
            exit 1
            