on:
  push:
    branches:
    -  main

jobs:
  check_code:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Main Branch
      - uses: action/checkout@v4

      - name: Echo Status
      - run: echo "::success workflow executed"
